{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibminitel/1.4.0/klibminitel-1.4.0.module",
    "group": "org.jraf.klibminitel",
    "module": "klibminitel",
    "version": "1.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.8.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "klibminitel-macosArm64Main-1.4.0.klib",
          "url": "klibminitel-macosarm64-1.4.0.klib",
          "size": 69678,
          "sha512": "ee785fe8706c5d0778bb1e5b7bcb9befb23e9496b918b7a3dac55103e2c4b89c6b7424f0fb3cd027eb1f79a1c6c80796d02b03db71f59e3fb64a8cbad38c3a79",
          "sha256": "52686d574364e1e4aaf39c1d47e4436dd76e848bc14b8fcc215e42bf4fce1bd4",
          "sha1": "d9553b7e1ad1e6e988ef4ee72cefe44b89de7f57",
          "md5": "8147adf55d55096bc3bcf74098dc26ba"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "klibminitel-macosarm64-1.4.0-sources.jar",
          "url": "klibminitel-macosarm64-1.4.0-sources.jar",
          "size": 18887,
          "sha512": "6f5b1a003e8609c4379729bf1133702c94c584d6d031bfc3a1b1bb0c0af5e5e371ed18bebd290cc99e70e0674a236eda5958253c0d742df86059601af1051401",
          "sha256": "416fcd209557466310ef7fd5f20988fa9c3692b7b8ff4fe015d98ca5cbe98fcd",
          "sha1": "8b673128b2848667a1ad4d80c6d6b6045fdb2258",
          "md5": "3eabd6387c5f4cffbeba13dd718a6376"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.8.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "klibminitel-macosarm64-1.4.0-metadata.jar",
          "url": "klibminitel-macosarm64-1.4.0-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
