{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibminitel/1.4.0/klibminitel-1.4.0.module",
    "group": "org.jraf.klibminitel",
    "module": "klibminitel",
    "version": "1.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.8.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "klibminitel-linuxX64Main-1.4.0.klib",
          "url": "klibminitel-linuxx64-1.4.0.klib",
          "size": 69666,
          "sha512": "e43b4d7e316cd11c4533fd9cde6aa70e3b037a616599c17a31af5015be06828323a00620c5d791761a979716bcf69a90c0f799901ed112ee806c8d31aad947dc",
          "sha256": "ee0f2f3e1ae22d4cce7b97c8995efff55e300209f1747ad9390363ce76cc2cc1",
          "sha1": "659071d8b9d430862d183a17e23f69a281744e93",
          "md5": "7c255d106909202021dddcf83b81f7ae"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "klibminitel-linuxx64-1.4.0-sources.jar",
          "url": "klibminitel-linuxx64-1.4.0-sources.jar",
          "size": 18887,
          "sha512": "6f5b1a003e8609c4379729bf1133702c94c584d6d031bfc3a1b1bb0c0af5e5e371ed18bebd290cc99e70e0674a236eda5958253c0d742df86059601af1051401",
          "sha256": "416fcd209557466310ef7fd5f20988fa9c3692b7b8ff4fe015d98ca5cbe98fcd",
          "sha1": "8b673128b2848667a1ad4d80c6d6b6045fdb2258",
          "md5": "3eabd6387c5f4cffbeba13dd718a6376"
        }
      ]
    }
  ]
}
