{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jraf.klibminitel",
    "module": "klibminitel",
    "version": "1.4.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "klibminitel-metadata-1.4.1-SNAPSHOT.jar",
          "url": "klibminitel-1.4.1-SNAPSHOT.jar",
          "size": 12965,
          "sha512": "9af01ece1cf43c6120a6bb8f2e7cb90fde78be5e1a04b0b59c317214238371f83ad8393fbeb5e469ec003aa18d018b08e5583067362c1e283b5201473b8cd35e",
          "sha256": "ca1f4391b3926338bdc2f1906cc3ae44c75f621d4f3adf6cdfde2851c759a8c8",
          "sha1": "55dbd941a352da19cf49294060f486a19e5d4410",
          "md5": "6a39960d7e737f87389072b07b0b1783"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "klibminitel-kotlin-1.4.1-SNAPSHOT-sources.jar",
          "url": "klibminitel-1.4.1-SNAPSHOT-sources.jar",
          "size": 18894,
          "sha512": "29823cd4a9c9789d0e50dfdb05cc235e5782169abc143260f631aa880bc8d3f2d1558ece5c23423e35bca7292a1decf67592154ac17fd2d56583af6401960bcc",
          "sha256": "d36d75f60378080ef6437c84545458d33776e9e915075b7b789a8bc2f06a29bf",
          "sha1": "bb3ea6a0fafd727cc7c9e713f7fd9e2dbb0515b9",
          "md5": "93b049f6f1974685c9e54127239ee708"
        }
      ]
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../klibminitel-jvm/1.4.1-SNAPSHOT/klibminitel-jvm-1.4.1-SNAPSHOT.module",
        "group": "org.jraf.klibminitel",
        "module": "klibminitel-jvm",
        "version": "1.4.1-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../klibminitel-jvm/1.4.1-SNAPSHOT/klibminitel-jvm-1.4.1-SNAPSHOT.module",
        "group": "org.jraf.klibminitel",
        "module": "klibminitel-jvm",
        "version": "1.4.1-SNAPSHOT"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../klibminitel-jvm/1.4.1-SNAPSHOT/klibminitel-jvm-1.4.1-SNAPSHOT.module",
        "group": "org.jraf.klibminitel",
        "module": "klibminitel-jvm",
        "version": "1.4.1-SNAPSHOT"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibminitel-linuxarm64/1.4.1-SNAPSHOT/klibminitel-linuxarm64-1.4.1-SNAPSHOT.module",
        "group": "org.jraf.klibminitel",
        "module": "klibminitel-linuxarm64",
        "version": "1.4.1-SNAPSHOT"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibminitel-linuxarm64/1.4.1-SNAPSHOT/klibminitel-linuxarm64-1.4.1-SNAPSHOT.module",
        "group": "org.jraf.klibminitel",
        "module": "klibminitel-linuxarm64",
        "version": "1.4.1-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibminitel-linuxx64/1.4.1-SNAPSHOT/klibminitel-linuxx64-1.4.1-SNAPSHOT.module",
        "group": "org.jraf.klibminitel",
        "module": "klibminitel-linuxx64",
        "version": "1.4.1-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibminitel-linuxx64/1.4.1-SNAPSHOT/klibminitel-linuxx64-1.4.1-SNAPSHOT.module",
        "group": "org.jraf.klibminitel",
        "module": "klibminitel-linuxx64",
        "version": "1.4.1-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibminitel-macosarm64/1.4.1-SNAPSHOT/klibminitel-macosarm64-1.4.1-SNAPSHOT.module",
        "group": "org.jraf.klibminitel",
        "module": "klibminitel-macosarm64",
        "version": "1.4.1-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibminitel-macosarm64/1.4.1-SNAPSHOT/klibminitel-macosarm64-1.4.1-SNAPSHOT.module",
        "group": "org.jraf.klibminitel",
        "module": "klibminitel-macosarm64",
        "version": "1.4.1-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibminitel-macosarm64/1.4.1-SNAPSHOT/klibminitel-macosarm64-1.4.1-SNAPSHOT.module",
        "group": "org.jraf.klibminitel",
        "module": "klibminitel-macosarm64",
        "version": "1.4.1-SNAPSHOT"
      }
    }
  ]
}
