{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibminitel/1.4.1-SNAPSHOT/klibminitel-1.4.1-SNAPSHOT.module",
    "group": "org.jraf.klibminitel",
    "module": "klibminitel",
    "version": "1.4.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.8.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "klibminitel-macosArm64Main-1.4.1-SNAPSHOT.klib",
          "url": "klibminitel-macosarm64-1.4.1-SNAPSHOT.klib",
          "size": 69685,
          "sha512": "82a52373198202cc74d4925b914d18676349c0ddf8bf7247d013ea482abcf39de81085bcfea5ec2ba16f4157b7a550762e235fa105c9fe8a592d7779792deba2",
          "sha256": "f87c41907afb075a858f2c306fbef01bc4c0e0e90327f599c75d76dde9567a4a",
          "sha1": "809f4a53d2798a445eb5ba67ba9a6275a2d82418",
          "md5": "8ac85a54e4b6b147deb117f5c152fc30"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "klibminitel-macosarm64-1.4.1-SNAPSHOT-sources.jar",
          "url": "klibminitel-macosarm64-1.4.1-SNAPSHOT-sources.jar",
          "size": 18894,
          "sha512": "29823cd4a9c9789d0e50dfdb05cc235e5782169abc143260f631aa880bc8d3f2d1558ece5c23423e35bca7292a1decf67592154ac17fd2d56583af6401960bcc",
          "sha256": "d36d75f60378080ef6437c84545458d33776e9e915075b7b789a8bc2f06a29bf",
          "sha1": "bb3ea6a0fafd727cc7c9e713f7fd9e2dbb0515b9",
          "md5": "93b049f6f1974685c9e54127239ee708"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.8.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "klibminitel-macosarm64-1.4.1-SNAPSHOT-metadata.jar",
          "url": "klibminitel-macosarm64-1.4.1-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
