{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibminitel/1.4.1-SNAPSHOT/klibminitel-1.4.1-SNAPSHOT.module",
    "group": "org.jraf.klibminitel",
    "module": "klibminitel",
    "version": "1.4.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20-Beta2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "klibminitel-macosArm64Main-1.4.1-SNAPSHOT.klib",
          "url": "klibminitel-macosarm64-1.4.1-SNAPSHOT.klib",
          "size": 69760,
          "sha512": "fde7f8c88b3b7ad077193890037711f3f75b52406502e03f4b3c70fd400b87649063a6b4afd7607854f493934a816f0ea12962a78ce5ae9e6c6d4b195617a704",
          "sha256": "bce7b8f65914c11dd19d48050ae3c9ad72e4d7c5d908ab89559e7951e0dc42db",
          "sha1": "ed6863962cb38cfbc943d73e147d3e043f173e47",
          "md5": "cf2cce591958b1c6ae4cfbdf071fb09b"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "klibminitel-macosarm64-1.4.1-SNAPSHOT-sources.jar",
          "url": "klibminitel-macosarm64-1.4.1-SNAPSHOT-sources.jar",
          "size": 18904,
          "sha512": "723694174f08b4d4bcde746991a484b837ac56463b4431ca673b413660b9af5222e663e271edc89d19eba25240eee6b89d2a9037b1f53967fb3bbbdd5e0147a0",
          "sha256": "d492673f97cb9861280ac5a718503889ceb0b4afa88c0c5ab8f1c6d6bc0e90e1",
          "sha1": "c0ed57d413be87f389f31ae28067e4a3d0ee7e68",
          "md5": "90835b61ef423ab22ef9005f30db5a45"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20-Beta2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "klibminitel-macosarm64-1.4.1-SNAPSHOT-metadata.jar",
          "url": "klibminitel-macosarm64-1.4.1-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
