{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jraf.klibminitel",
    "module": "klibminitel",
    "version": "1.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.8.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "klibminitel-metadata-1.4.0-SNAPSHOT.jar",
          "url": "klibminitel-1.4.0-SNAPSHOT.jar",
          "size": 12957,
          "sha512": "e6b6849e945f78d8a805439d762987befd5b113f8abf7109a269a83e5c03475958bb275cbb480614986fa62bbb279df450b3330efc4e2d7f5fcaf153c08a435e",
          "sha256": "40a6ba45ac7178ebc4783034b58782d042a1205baed97c4a6e2ee471f1ba94ae",
          "sha1": "74217918a33c3d5e2350af4f973905707dfef4b7",
          "md5": "ce2af8a748219e6e03ab406f0d15bfa6"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "klibminitel-kotlin-1.4.0-SNAPSHOT-sources.jar",
          "url": "klibminitel-1.4.0-SNAPSHOT-sources.jar",
          "size": 18895,
          "sha512": "31aeffb19f85ac5dab54ab42c20dcfcb42cd47531e3e625e277fc96a9367aa8d684eabfe517d8b8b74d38438c28921756ff99754a0743c5655dd00f3fb724558",
          "sha256": "99205ae40b275331de6fb91445d2ebb0bc019b6c33dfd42d2d3bcdcefcf8b70e",
          "sha1": "0c42beb0ac735cb8cbd93f40ca94457c5c883419",
          "md5": "fdabab372dab0a122daa6cf68da41da3"
        }
      ]
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../klibminitel-jvm/1.4.0-SNAPSHOT/klibminitel-jvm-1.4.0-SNAPSHOT.module",
        "group": "org.jraf.klibminitel",
        "module": "klibminitel-jvm",
        "version": "1.4.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../klibminitel-jvm/1.4.0-SNAPSHOT/klibminitel-jvm-1.4.0-SNAPSHOT.module",
        "group": "org.jraf.klibminitel",
        "module": "klibminitel-jvm",
        "version": "1.4.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../klibminitel-jvm/1.4.0-SNAPSHOT/klibminitel-jvm-1.4.0-SNAPSHOT.module",
        "group": "org.jraf.klibminitel",
        "module": "klibminitel-jvm",
        "version": "1.4.0-SNAPSHOT"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibminitel-linuxarm64/1.4.0-SNAPSHOT/klibminitel-linuxarm64-1.4.0-SNAPSHOT.module",
        "group": "org.jraf.klibminitel",
        "module": "klibminitel-linuxarm64",
        "version": "1.4.0-SNAPSHOT"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibminitel-linuxarm64/1.4.0-SNAPSHOT/klibminitel-linuxarm64-1.4.0-SNAPSHOT.module",
        "group": "org.jraf.klibminitel",
        "module": "klibminitel-linuxarm64",
        "version": "1.4.0-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibminitel-linuxx64/1.4.0-SNAPSHOT/klibminitel-linuxx64-1.4.0-SNAPSHOT.module",
        "group": "org.jraf.klibminitel",
        "module": "klibminitel-linuxx64",
        "version": "1.4.0-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibminitel-linuxx64/1.4.0-SNAPSHOT/klibminitel-linuxx64-1.4.0-SNAPSHOT.module",
        "group": "org.jraf.klibminitel",
        "module": "klibminitel-linuxx64",
        "version": "1.4.0-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibminitel-macosarm64/1.4.0-SNAPSHOT/klibminitel-macosarm64-1.4.0-SNAPSHOT.module",
        "group": "org.jraf.klibminitel",
        "module": "klibminitel-macosarm64",
        "version": "1.4.0-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibminitel-macosarm64/1.4.0-SNAPSHOT/klibminitel-macosarm64-1.4.0-SNAPSHOT.module",
        "group": "org.jraf.klibminitel",
        "module": "klibminitel-macosarm64",
        "version": "1.4.0-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibminitel-macosarm64/1.4.0-SNAPSHOT/klibminitel-macosarm64-1.4.0-SNAPSHOT.module",
        "group": "org.jraf.klibminitel",
        "module": "klibminitel-macosarm64",
        "version": "1.4.0-SNAPSHOT"
      }
    }
  ]
}
