{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibminitel/1.4.1-SNAPSHOT/klibminitel-1.4.1-SNAPSHOT.module",
    "group": "org.jraf.klibminitel",
    "module": "klibminitel",
    "version": "1.4.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20-Beta2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "klibminitel-linuxX64Main-1.4.1-SNAPSHOT.klib",
          "url": "klibminitel-linuxx64-1.4.1-SNAPSHOT.klib",
          "size": 69680,
          "sha512": "4772e5d27c61314fca0a06422efb3a6bcafb22de9c1d6acb2722d160e8caca5be8089294dd1b47badabf3ee7bba7f1d17aa4fc8768a1dfe45b42835135484d96",
          "sha256": "6578eb3228acc168c458cefd87b6c7407f566882c2493f5b87641d623ce47c81",
          "sha1": "d8a758fbd7a6f37ce85d94652dc3e507f824958e",
          "md5": "382aaedaa779b466766f12c301c5b562"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "klibminitel-linuxx64-1.4.1-SNAPSHOT-sources.jar",
          "url": "klibminitel-linuxx64-1.4.1-SNAPSHOT-sources.jar",
          "size": 18894,
          "sha512": "29823cd4a9c9789d0e50dfdb05cc235e5782169abc143260f631aa880bc8d3f2d1558ece5c23423e35bca7292a1decf67592154ac17fd2d56583af6401960bcc",
          "sha256": "d36d75f60378080ef6437c84545458d33776e9e915075b7b789a8bc2f06a29bf",
          "sha1": "bb3ea6a0fafd727cc7c9e713f7fd9e2dbb0515b9",
          "md5": "93b049f6f1974685c9e54127239ee708"
        }
      ]
    }
  ]
}
