{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibminitel/1.4.1-SNAPSHOT/klibminitel-1.4.1-SNAPSHOT.module",
    "group": "org.jraf.klibminitel",
    "module": "klibminitel",
    "version": "1.4.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20-Beta2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "klibminitel-linuxX64Main-1.4.1-SNAPSHOT.klib",
          "url": "klibminitel-linuxx64-1.4.1-SNAPSHOT.klib",
          "size": 69747,
          "sha512": "2f0b8d4a01e0aa7a62fa67510b2d2f84bf85c46c3dcbaa5474db3c3e1e1a2099d6a8c1a3f6a8bc32f9931ac332aaa862b869873ab7580d778bec6722420a2ca8",
          "sha256": "654962f4ba0db06f13c2a88a8082472d6ce6ce5ec6b81ef4dc879af610e2ea27",
          "sha1": "be08be10af4181565fbb4d3ddd48dfc36e42bbc0",
          "md5": "d379a732a943955fb97935d0168be3de"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "klibminitel-linuxx64-1.4.1-SNAPSHOT-sources.jar",
          "url": "klibminitel-linuxx64-1.4.1-SNAPSHOT-sources.jar",
          "size": 18904,
          "sha512": "723694174f08b4d4bcde746991a484b837ac56463b4431ca673b413660b9af5222e663e271edc89d19eba25240eee6b89d2a9037b1f53967fb3bbbdd5e0147a0",
          "sha256": "d492673f97cb9861280ac5a718503889ceb0b4afa88c0c5ab8f1c6d6bc0e90e1",
          "sha1": "c0ed57d413be87f389f31ae28067e4a3d0ee7e68",
          "md5": "90835b61ef423ab22ef9005f30db5a45"
        }
      ]
    }
  ]
}
