{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibminitel/1.4.0-SNAPSHOT/klibminitel-1.4.0-SNAPSHOT.module",
    "group": "org.jraf.klibminitel",
    "module": "klibminitel",
    "version": "1.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.8.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "klibminitel-linuxArm64Main-1.4.0-SNAPSHOT.klib",
          "url": "klibminitel-linuxarm64-1.4.0-SNAPSHOT.klib",
          "size": 69685,
          "sha512": "734af2478777c05d718694b2f0a0d8f8cf7cf5dfc58b5f630be49180bbbef6ac10ab7b46e2bfc88c90df7fcfbed57ffe2819af12e874b5ea720727c31a2ef07a",
          "sha256": "6ad4d9c4b4af05668d78f863bfbdc5ea6c38c8ab17b75629faf5112f225cda67",
          "sha1": "d0ed7708ecb2ab99c1793cd1a760bd0b19db2ceb",
          "md5": "e73fb5e7e145f2ecfcf47473165dabf3"
        }
      ]
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "klibminitel-linuxarm64-1.4.0-SNAPSHOT-sources.jar",
          "url": "klibminitel-linuxarm64-1.4.0-SNAPSHOT-sources.jar",
          "size": 18895,
          "sha512": "31aeffb19f85ac5dab54ab42c20dcfcb42cd47531e3e625e277fc96a9367aa8d684eabfe517d8b8b74d38438c28921756ff99754a0743c5655dd00f3fb724558",
          "sha256": "99205ae40b275331de6fb91445d2ebb0bc019b6c33dfd42d2d3bcdcefcf8b70e",
          "sha1": "0c42beb0ac735cb8cbd93f40ca94457c5c883419",
          "md5": "fdabab372dab0a122daa6cf68da41da3"
        }
      ]
    }
  ]
}
