{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibminitel/1.4.1-SNAPSHOT/klibminitel-1.4.1-SNAPSHOT.module",
    "group": "org.jraf.klibminitel",
    "module": "klibminitel",
    "version": "1.4.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.8.2"
          }
        }
      ],
      "files": [
        {
          "name": "klibminitel-jvm-1.4.1-SNAPSHOT.jar",
          "url": "klibminitel-jvm-1.4.1-SNAPSHOT.jar",
          "size": 102475,
          "sha512": "91013eaa8f29b093d3791592cc1e725514113789bcef67d8abd984beb637da3f27ae03d4a1752a90b3990d08026593313cb7468087bb770f105f191020860657",
          "sha256": "04371f545535b2dc01613d17c53f98603aa5e29068d8daf5e2ce01a58c83e4d7",
          "sha1": "6f4087c29bc7fd3705862d8706b7eb7869d907bf",
          "md5": "734d6c9ee1bf475eced5286d71ec6b2c"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk9",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "klibminitel-jvm-1.4.1-SNAPSHOT.jar",
          "url": "klibminitel-jvm-1.4.1-SNAPSHOT.jar",
          "size": 102475,
          "sha512": "91013eaa8f29b093d3791592cc1e725514113789bcef67d8abd984beb637da3f27ae03d4a1752a90b3990d08026593313cb7468087bb770f105f191020860657",
          "sha256": "04371f545535b2dc01613d17c53f98603aa5e29068d8daf5e2ce01a58c83e4d7",
          "sha1": "6f4087c29bc7fd3705862d8706b7eb7869d907bf",
          "md5": "734d6c9ee1bf475eced5286d71ec6b2c"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "klibminitel-jvm-1.4.1-SNAPSHOT-sources.jar",
          "url": "klibminitel-jvm-1.4.1-SNAPSHOT-sources.jar",
          "size": 24164,
          "sha512": "2cfcf494d34f16d8b2aff13e13a4d0e60fae379989647987b415a680617e3501c8e7131fdb6d4ba9b10c69574c0071bf7e969e165dc059cfab014dfe093611b3",
          "sha256": "c8b21f29f541b8cee9a9ab443c6d50c8c9cf5a16e5cc3455dc08fb7b0bfd87b9",
          "sha1": "566cb3ee35accd7d7df833d30979900bf49d1fba",
          "md5": "80bd5fc92e96eeaf32de7e3f20908ae8"
        }
      ]
    }
  ]
}
