{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibminitel/1.4.1-SNAPSHOT/klibminitel-1.4.1-SNAPSHOT.module",
    "group": "org.jraf.klibminitel",
    "module": "klibminitel",
    "version": "1.4.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.8.2"
          }
        }
      ],
      "files": [
        {
          "name": "klibminitel-jvm-1.4.1-SNAPSHOT.jar",
          "url": "klibminitel-jvm-1.4.1-SNAPSHOT.jar",
          "size": 92804,
          "sha512": "199b2c78f2550c59541d956812ad11982c845519433981ebacbd3e93d6689ab02e5c92f16c3ef1373410976eb7ec668e9f3f2c1e2f3879278a8fcbc7c31f3fa9",
          "sha256": "05eba74945070cbc1675371715b50a7c847571a859de18a7a5163957f1964a2b",
          "sha1": "defaf8130eef3e3bbf39e071b81564b224bfbad9",
          "md5": "a7fc76fe00afb6e09bcbb876c88f9ef5"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk9",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "klibminitel-jvm-1.4.1-SNAPSHOT.jar",
          "url": "klibminitel-jvm-1.4.1-SNAPSHOT.jar",
          "size": 92804,
          "sha512": "199b2c78f2550c59541d956812ad11982c845519433981ebacbd3e93d6689ab02e5c92f16c3ef1373410976eb7ec668e9f3f2c1e2f3879278a8fcbc7c31f3fa9",
          "sha256": "05eba74945070cbc1675371715b50a7c847571a859de18a7a5163957f1964a2b",
          "sha1": "defaf8130eef3e3bbf39e071b81564b224bfbad9",
          "md5": "a7fc76fe00afb6e09bcbb876c88f9ef5"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "klibminitel-jvm-1.4.1-SNAPSHOT-sources.jar",
          "url": "klibminitel-jvm-1.4.1-SNAPSHOT-sources.jar",
          "size": 23599,
          "sha512": "233750977ab994f7cba27a22e9a3e60fc9d705f556866b92befbb30c8e2f284a0130f2b5d2e8b65278da9635c0b32c809bd5a5fb3542b4b471391bd569ae7d3d",
          "sha256": "f678a7dda876f71e3eaed381609e239369eaa685a2f08d82d710a5eacbe3deb4",
          "sha1": "a6c929c67049d665ec49dd0e04eb5d7baad997ea",
          "md5": "5b65ae9af9e00caeb264340b5e35ed63"
        }
      ]
    }
  ]
}
