{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibminitel/1.4.0/klibminitel-1.4.0.module",
    "group": "org.jraf.klibminitel",
    "module": "klibminitel",
    "version": "1.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.8.2",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "klibminitel-jvm-1.4.0.jar",
          "url": "klibminitel-jvm-1.4.0.jar",
          "size": 92801,
          "sha512": "9caac26e601a9214ecec0cf2a83cc4040e16a57cccbe7177f7d123ee2608c92f53006ac08564c6af6d3c9e07c244202db355ceca2b53d4735747b798b0a5a8d7",
          "sha256": "6f687ca3a33d19f9698384f7038a7fda9be5c3e01e5e8a4df52120defbf735aa",
          "sha1": "663b047ed9936e34bc762bbb6a2f7ee068cc70c6",
          "md5": "b42893412647eceea06336fabe449495"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.8.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk9",
          "version": {
            "requires": "1.10.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "klibminitel-jvm-1.4.0.jar",
          "url": "klibminitel-jvm-1.4.0.jar",
          "size": 92801,
          "sha512": "9caac26e601a9214ecec0cf2a83cc4040e16a57cccbe7177f7d123ee2608c92f53006ac08564c6af6d3c9e07c244202db355ceca2b53d4735747b798b0a5a8d7",
          "sha256": "6f687ca3a33d19f9698384f7038a7fda9be5c3e01e5e8a4df52120defbf735aa",
          "sha1": "663b047ed9936e34bc762bbb6a2f7ee068cc70c6",
          "md5": "b42893412647eceea06336fabe449495"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "klibminitel-jvm-1.4.0-sources.jar",
          "url": "klibminitel-jvm-1.4.0-sources.jar",
          "size": 23592,
          "sha512": "ce11f426fc735c75929b18b69b51c36601ecb8da7d2d8afcd2f9bbb62442471cb9a5c785fe4c428f5b9f4caf20a4755b42123e5a8dbd578a7f68ea672531633f",
          "sha256": "9486dfd94151e4c96166801c9e0d2bafba6a491217205df1b514ba1a35c6a32d",
          "sha1": "89474bdd0d1c529a3d323ad885e769ef4ad7dd3e",
          "md5": "62f801a0f5aff4d67eea1027e922aeba"
        }
      ]
    }
  ]
}
