{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibminitel/1.4.1-SNAPSHOT/klibminitel-1.4.1-SNAPSHOT.module",
    "group": "org.jraf.klibminitel",
    "module": "klibminitel",
    "version": "1.4.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20-Beta2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "klibminitel-linuxArm64Main-1.4.1-SNAPSHOT.klib",
          "url": "klibminitel-linuxarm64-1.4.1-SNAPSHOT.klib",
          "size": 69760,
          "sha512": "7878e4ee08f73507b6555d171a03c1ddb2e80f7aad625330c58141eb9b4b717d77c820ddec310177b58dfd7ebb58cf70ed59b9917c8e5efa203caa057f6928c3",
          "sha256": "013154d498c58d7b90a82e35def985f57f9433be6e562dafba28e4c1cecb3c97",
          "sha1": "2e081238d13bb25247f34216c9308646ff259937",
          "md5": "ab583b7d5cb133619d977ce0bafc39cc"
        }
      ]
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "klibminitel-linuxarm64-1.4.1-SNAPSHOT-sources.jar",
          "url": "klibminitel-linuxarm64-1.4.1-SNAPSHOT-sources.jar",
          "size": 18904,
          "sha512": "723694174f08b4d4bcde746991a484b837ac56463b4431ca673b413660b9af5222e663e271edc89d19eba25240eee6b89d2a9037b1f53967fb3bbbdd5e0147a0",
          "sha256": "d492673f97cb9861280ac5a718503889ceb0b4afa88c0c5ab8f1c6d6bc0e90e1",
          "sha1": "c0ed57d413be87f389f31ae28067e4a3d0ee7e68",
          "md5": "90835b61ef423ab22ef9005f30db5a45"
        }
      ]
    }
  ]
}
