{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibminitel/1.4.1-SNAPSHOT/klibminitel-1.4.1-SNAPSHOT.module",
    "group": "org.jraf.klibminitel",
    "module": "klibminitel",
    "version": "1.4.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.8.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "klibminitel-linuxArm64Main-1.4.1-SNAPSHOT.klib",
          "url": "klibminitel-linuxarm64-1.4.1-SNAPSHOT.klib",
          "size": 69686,
          "sha512": "6b5089c64daccd73d47a9eb9111c35e1d4927d1f9d7bba81a3521e3c2e1c8d74fb22297b80f804c3cfeee9763cb385ce52f4ebeece7d161511c58f9ca8459cfe",
          "sha256": "208ab9204ed157c5bee4d5ac9acb701f6b0de39fe8489a0074ff6d89ed59cf0d",
          "sha1": "3cac8fde3a021c44fcd4c147571bd256c918b6c5",
          "md5": "f15dce79eee83bdd5bf562ad7c35eb08"
        }
      ]
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "klibminitel-linuxarm64-1.4.1-SNAPSHOT-sources.jar",
          "url": "klibminitel-linuxarm64-1.4.1-SNAPSHOT-sources.jar",
          "size": 18894,
          "sha512": "29823cd4a9c9789d0e50dfdb05cc235e5782169abc143260f631aa880bc8d3f2d1558ece5c23423e35bca7292a1decf67592154ac17fd2d56583af6401960bcc",
          "sha256": "d36d75f60378080ef6437c84545458d33776e9e915075b7b789a8bc2f06a29bf",
          "sha1": "bb3ea6a0fafd727cc7c9e713f7fd9e2dbb0515b9",
          "md5": "93b049f6f1974685c9e54127239ee708"
        }
      ]
    }
  ]
}
